"""Keyword taxonomies for Stage 2 of the classifier pipeline.

These dictionaries are the bot's opinion about what each phrase *means*.
Tune the weights over time as you see what the composite `check_risk_score`
and `fit_score` produce on real postings.

All keys are matched case-insensitively as whole tokens with word boundaries
(see regex_pass.py).

Profile alignment (April 2026):
    Mohammad Abu Dagar — Founding Engineer at Vimy Systèmes; ECE496Y1
    capstone (Bell-412 autonomy stack: ROS, LVI-SAM, NMPC); Tenstorrent
    qualification engineering (Wormhole/Grayskull silicon bring-up); ships
    agentic AI side projects (this very bot, Reel_block, GeniusActivities).
    Best fits — applied-AI / autonomy-systems engineer at Series A-B
    robotics, defence-tech, or AI-tooling startups. Toronto / remote-CA / -US.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# STRICT — correlates with enhanced / fingerprint / credit / clearance checks.
# Weight 0..1. Multi-match is superlinear (diminishing returns) in regex_pass.
# ---------------------------------------------------------------------------
STRICT_KEYWORDS: dict[str, float] = {
    # Government / defence (still flag — even though defence-adjacent is a TARGET,
    # active clearance gating is a real BG-check signal we want to surface)
    "public trust clearance": 1.0,
    "reliability status": 1.0,
    "secret clearance": 1.0,
    "top secret": 1.0,
    "ts/sci": 1.0,
    "security clearance": 0.9,
    "active clearance": 1.0,
    "active security clearance": 1.0,
    "must hold an active": 0.8,
    "canadian citizen required": 0.9,
    "canadian citizenship required": 0.9,
    "must be a canadian citizen": 0.9,
    "us citizen required": 0.9,
    "us citizenship required": 0.9,
    "controlled goods program": 1.0,
    "itar": 1.0,
    "ear controlled": 0.7,
    "ear-controlled": 0.7,
    "export control": 0.7,
    "export-controlled": 0.7,
    "csis": 1.0,
    "cse canada": 0.9,
    "dnd cleared": 0.9,
    "pspc": 0.7,
    # Financial services
    "soc 2": 0.5,
    "soc2": 0.5,
    "pci-dss": 0.8,
    "pci dss": 0.8,
    "osfi-regulated": 0.9,
    "osfi regulated": 0.9,
    "osfi": 0.6,
    "bondable": 0.9,
    "fintrac": 0.8,
    "iiroc": 0.8,
    "aml/kyc": 0.6,
    "anti-money laundering": 0.6,
    "anti money laundering": 0.6,
    # Healthcare / vulnerable
    "vulnerable sector check": 1.0,
    "vulnerable sector": 0.9,
    "phipa": 0.7,
    "hipaa": 0.6,
    "working with minors": 1.0,
    "working with children": 1.0,
    # Generic elevated
    "fingerprint check": 1.0,
    "fingerprints required": 1.0,
    "enhanced police check": 0.9,
    "enhanced background check": 0.8,
    "credit check required": 0.8,
    "sterling": 0.3,
    "hireright": 0.3,
    "checkr enhanced": 0.6,
    "7-year employment verification": 0.5,
    "background check required": 0.4,  # generic; weak on its own
}

# ---------------------------------------------------------------------------
# LENIENT — correlates with conviction-only basic check or no check.
# ---------------------------------------------------------------------------
LENIENT_KEYWORDS: dict[str, float] = {
    "founding engineer": 0.7,
    "founding member": 0.6,
    "early engineer": 0.6,
    "seed stage": 0.5,
    "seed-stage": 0.5,
    "series a": 0.5,
    "series b": 0.5,
    "y combinator": 0.5,
    "yc-backed": 0.5,
    "yc backed": 0.5,
    "yc s2": 0.4,  # YC batch nomenclature; partial match
    "yc w2": 0.4,
    "bootstrapped": 0.5,
    "open source": 0.3,
    "open-source": 0.3,
    "we contribute upstream": 0.4,
    "async-first": 0.3,
    "async first": 0.3,
    "no clearance required": 0.8,
    "no security clearance": 0.8,
    "clearance not required": 0.8,
    "clearance to be sponsored": 0.7,
    "willing to sponsor": 0.4,
    "contract role": 0.4,
    "freelance": 0.6,
    "1099": 0.5,
    "certn basic": 0.9,
    "remote canada": 0.5,
    "remote-canada": 0.5,
    "canada remote": 0.5,
}

# ---------------------------------------------------------------------------
# FIT — correlates with the operator's specific skills.
# Weights are aggressive (2.0 .. 3.5) because hits here are decisive.
# Profile-aligned: applied-AI / autonomy-systems / robotics / defence-dual-use
# / AI-tooling / silicon-software seam. Anti-keywords carry negative weight.
# ---------------------------------------------------------------------------
FIT_KEYWORDS: dict[str, float] = {
    # ─── APPLIED AI / AGENTIC / LLM TOOLING ─────────────────────── (top tier)
    "rag": 3.5,
    "retrieval-augmented": 3.5,
    "retrieval augmented": 3.5,
    "vector database": 3.0,
    "vector store": 3.0,
    "embeddings": 2.5,
    "embedding model": 2.5,
    "pgvector": 3.0,
    "agentic": 3.5,
    "ai agent": 3.5,
    "ai agents": 3.5,
    "agent framework": 3.5,
    "tool use": 3.0,
    "tool-use": 3.0,
    "function calling": 3.0,
    "function-calling": 3.0,
    "prompt caching": 3.5,
    "prompt engineering": 2.5,
    "llm evaluation": 3.5,
    "llm eval": 3.5,
    "model evaluation": 2.5,
    "anthropic": 3.5,
    "claude": 3.0,
    "openai api": 2.5,
    "gpt-4": 2.0,
    "gemini api": 2.0,
    "ollama": 3.0,
    "langchain": 3.0,
    "llamaindex": 3.0,
    "llama index": 3.0,
    "applied ai": 3.5,
    "applied-ai": 3.5,
    "ai engineer": 3.5,
    "ml engineer": 2.5,
    "human-in-the-loop": 3.0,
    "human in the loop": 3.0,
    "ai-assisted": 3.0,
    "ai-augmented": 3.0,
    "ai pair programming": 3.0,
    "ai coding": 3.5,
    "ai-coding": 3.5,
    "ai coding tools": 3.5,
    "developer tools for ai": 3.5,
    "ai developer tools": 3.5,
    "ai dev tools": 3.5,
    "code generation": 2.5,
    "copilot": 2.0,
    # ─── AUTONOMY / ROBOTICS ────────────────────────────────────── (top tier)
    "ros": 3.5,
    "ros2": 3.5,
    "ros 2": 3.5,
    "rosbag": 2.5,
    "gazebo": 3.0,
    "isaac sim": 3.0,
    "isaac-sim": 3.0,
    "slam": 3.5,
    "vio": 3.5,
    "visual-inertial": 3.5,
    "visual inertial": 3.5,
    "lidar": 3.0,
    "lidar slam": 3.5,
    "lvi-sam": 3.5,
    "loam": 3.0,
    "kimera": 3.5,
    "octomap": 3.5,
    "occupancy mapping": 3.0,
    "occupancy grid": 2.5,
    "ekf": 3.0,
    "extended kalman": 3.0,
    "kalman filter": 2.5,
    "particle filter": 2.5,
    "sensor fusion": 3.5,
    "multi-modal sensor fusion": 3.5,
    "perception": 2.5,
    "perception engineer": 3.5,
    "motion planning": 3.0,
    "trajectory optimization": 3.0,
    "trajectory generation": 3.0,
    "model predictive control": 3.5,
    "nonlinear mpc": 3.5,
    "mpc": 2.5,
    "nmpc": 3.5,
    "acado": 3.5,
    "qpoases": 3.5,
    "controls engineer": 3.0,
    "control systems": 2.5,
    "mavlink": 3.5,
    "px4": 3.0,
    "ardupilot": 3.0,
    "pixhawk": 3.0,
    "uav": 3.5,
    "uas": 3.5,
    "drone autonomy": 3.5,
    "drone software": 3.0,
    "autonomous vehicle": 3.0,
    "autonomous driving": 3.0,
    "self-driving": 3.0,
    "self driving": 3.0,
    "rotary-wing": 3.0,
    "rotorcraft": 3.0,
    "helicopter autonomy": 3.5,
    "fixed-wing": 2.5,
    "swarming": 3.0,
    "swarm robotics": 3.5,
    "gnss-denied": 3.5,
    "gnss denied": 3.5,
    "gps-denied": 3.5,
    "gps denied": 3.5,
    "counter-uas": 3.0,
    "counter uas": 3.0,
    # ─── DEFENCE / DUAL-USE ─────────────────────────────────────── (high)
    "dnd ideas": 3.5,
    "dnd": 1.5,
    "department of national defence": 2.5,
    "defence-tech": 3.0,
    "defense-tech": 3.0,
    "dual-use": 3.0,
    "dual use": 3.0,
    "dual-use technology": 3.5,
    "national security": 2.5,
    "do-178c": 3.0,
    "do178c": 3.0,
    "ieee 7001": 2.5,
    "ieee 7003": 2.5,
    "iso/iec 42001": 2.5,
    "iso 42001": 2.5,
    "explainable ai": 2.5,
    "ai governance": 2.5,
    "openlineage": 2.5,
    "prov-o": 2.5,
    "model lineage": 2.5,
    "data lineage": 2.5,
    # ─── SILICON-SOFTWARE / ML INFRA ────────────────────────────── (high)
    "tenstorrent": 3.5,
    "ai accelerator": 3.5,
    "ai accelerators": 3.5,
    "ai-accelerator": 3.5,
    "wormhole": 2.5,
    "grayskull": 2.5,
    "silicon bring-up": 3.5,
    "silicon bringup": 3.5,
    "silicon validation": 3.0,
    "silicon qualification": 3.5,
    "post-silicon": 3.0,
    "post silicon": 3.0,
    "rtl simulation": 2.5,
    "pcie": 3.0,
    "ddr bring-up": 3.0,
    "memory bring-up": 3.0,
    "test infrastructure": 2.5,
    "test harness": 2.5,
    "ml infrastructure": 3.0,
    "ml systems": 3.5,
    "ml-systems": 3.5,
    "inference engine": 3.0,
    "inference runtime": 3.0,
    "model serving": 3.0,
    "kernel": 2.5,
    "cuda kernel": 3.5,
    "cuda kernels": 3.5,
    "triton kernel": 3.5,
    "triton": 2.5,
    "compiler": 3.0,
    "llvm": 3.0,
    "mlir": 3.5,
    "tensorflow xla": 2.5,
    "torch.compile": 2.5,
    # ─── ML / DEEP LEARNING (general) ────────────────────────────── (mid-high)
    "pytorch": 3.0,
    "tensorflow": 2.0,
    "jax": 2.5,
    "deep learning": 2.5,
    "machine learning": 2.0,
    "computer vision": 3.0,
    "yolo": 2.5,
    "yolov8": 3.0,
    "opencv": 2.5,
    "transformers": 2.5,
    "huggingface": 2.0,
    "hugging face": 2.0,
    "diffusion model": 2.0,
    "fine-tuning": 2.0,
    "fine tuning": 2.0,
    "lora": 2.0,
    "qlora": 2.0,
    "model distillation": 2.0,
    # ─── SYSTEMS / CompE ─────────────────────────────────────────── (mid)
    "c++": 2.5,
    "c++17": 2.5,
    "c++20": 2.5,
    "rust": 2.5,
    "systems programming": 2.5,
    "embedded": 2.5,
    "firmware": 2.0,
    "fpga": 2.5,
    "real-time systems": 2.5,
    "real time systems": 2.5,
    "low-latency": 2.5,
    "low latency": 2.5,
    "linux kernel": 2.5,
    # ─── BACKEND / INFRA ─────────────────────────────────────────── (mid)
    "fastapi": 2.0,
    "postgres": 2.0,
    "postgresql": 2.0,
    "psycopg": 2.0,
    "alembic": 2.0,
    "sqlalchemy": 1.5,
    "redis": 1.5,
    "docker": 1.5,
    "github actions": 1.5,
    # ─── WEB / FRONTEND (still has signal — limiliminal, vimy.ai) ── (low-mid)
    "typescript": 1.5,
    "react": 1.5,
    "react 18": 1.5,
    "react 19": 1.5,
    "next.js": 2.0,
    "nextjs": 2.0,
    "next js": 2.0,
    "tailwind": 1.0,
    "node.js": 1.5,
    "nodejs": 1.5,
    "react three fiber": 3.0,
    "@react-three/drei": 3.0,
    "three.js": 2.5,
    "three js": 2.5,
    "framer motion": 2.0,
    "spline 3d": 2.0,
    # ─── MOBILE (Android with Compose — Reel_block, Redline, MyDrumpad) ─
    "kotlin": 2.0,
    "jetpack compose": 2.5,
    "android accessibility service": 3.0,
    "hilt": 2.0,
    "room database": 2.0,
    # ─── GRAPHICS (down-weighted vs. before — kept for completeness) ─
    "opengl": 1.5,
    "webgl": 2.0,
    "webgpu": 2.5,
    "vulkan": 2.0,
    "shader": 2.0,
    "glsl": 2.0,
    "hlsl": 2.0,
    "raytracing": 2.0,
    "ray tracing": 2.0,
    "rasterization": 1.5,
    "real-time rendering": 2.0,
    "neural rendering": 2.5,
    "gaussian splatting": 2.5,
    "nerf": 2.5,
    # ─── 5G / NETWORKING (down-weighted — was bullseye on old profile) ─
    "5g": 1.5,
    "oran": 1.5,
    "o-ran": 1.5,
    "lte": 1.0,
    "dpdk": 1.5,
    "p4 programming": 1.5,
}

# ---------------------------------------------------------------------------
# ANTI — presence reduces fit_score (no amount of other signal saves it).
# Weights are aggressive (2.0 .. 4.0) because off-target roles waste cycles.
# ---------------------------------------------------------------------------
ANTI_KEYWORDS: dict[str, float] = {
    # Pure design / creative work (user is engineer, not designer)
    "graphic designer": 4.0,
    "graphic design": 3.0,
    "adobe creative suite": 4.0,
    "adobe photoshop": 3.0,
    "adobe illustrator": 3.0,
    "indesign": 3.0,
    "after effects": 3.0,
    "creative agency": 3.0,
    "art director": 4.0,
    "ux/ui designer": 3.0,
    "visual designer": 3.0,
    "brand designer": 3.0,
    # Pure marketing / CMS / no-code
    "wordpress": 4.0,
    "shopify plugin": 4.0,
    "shopify partner": 3.0,
    "marketing automation": 2.5,
    "salesforce administrator": 3.0,
    "salesforce developer": 2.0,
    "sap consultant": 3.0,
    "sharepoint administrator": 3.0,
    "rpa developer": 3.0,
    "rpa engineer": 2.5,
    # Legacy stacks
    "cobol": 3.0,
    "mainframe": 3.0,
    "vb.net": 2.5,
    "abap": 3.0,
    # Adtech / gambling / crypto-casino (per prefs.md hard-no)
    "adtech": 3.0,
    "ad tech": 3.0,
    "digital advertising": 2.0,
    "online casino": 4.0,
    "sportsbook": 3.0,
    "igaming": 3.0,
    "i-gaming": 3.0,
    "sweepstakes": 3.0,
    "crypto casino": 4.0,
    "mlm": 4.0,
    "multi-level marketing": 4.0,
    # Pure PHP / WP-stack web
    "php developer": 3.0,
    "drupal developer": 2.5,
    "magento": 2.5,
}

# ---------------------------------------------------------------------------
# Role-category keywords — picks one category per posting.
# Order matters: first-match wins (see regex_pass.py if you change semantics).
# Reordered for the new ICP — applied_ai / autonomy / ai_tooling check first.
# ---------------------------------------------------------------------------
ROLE_CATEGORY_KEYWORDS: dict[str, list[str]] = {
    "applied_ai": [
        "applied ai", "applied-ai", "ai engineer", "ml engineer",
        "rag", "retrieval-augmented", "agentic", "ai agent",
        "llm engineer", "llm evaluation", "prompt engineering",
        "ai/ml engineer", "ai-ml engineer",
    ],
    "ai_tooling": [
        "ai coding", "ai-coding", "developer tools for ai",
        "ai dev tools", "ai developer tools",
        "ai pair programming", "code generation",
        "ai-augmented developer",
    ],
    "autonomy_robotics": [
        "ros", "slam", "vio", "perception engineer",
        "motion planning", "robotics engineer", "autonomy engineer",
        "self-driving", "autonomous vehicle", "autonomous driving",
        "drone autonomy", "uav", "uas", "rotorcraft",
        "controls engineer", "control systems engineer",
        "mpc", "nmpc", "model predictive control",
    ],
    "defence_dual_use": [
        "defence-tech", "defense-tech", "dual-use",
        "national security", "dnd ideas",
        "defense engineer", "defence engineer",
    ],
    "ml_systems": [
        "ml infrastructure", "ml systems", "ml-systems",
        "inference engine", "inference runtime", "model serving",
        "ai accelerator", "ai-accelerator",
        "silicon bring-up", "silicon validation", "silicon qualification",
        "cuda kernel", "triton kernel", "compiler engineer",
    ],
    "ml": [
        "machine learning", "deep learning", "pytorch",
        "tensorflow", "research scientist",
    ],
    "graphics": [
        "shader", "opengl", "vulkan", "webgl", "webgpu",
        "rendering engineer", "rasterization",
        "neural rendering", "gaussian splatting",
    ],
    "games": ["unreal", "unity", "game engine", "gameplay", "game developer"],
    "5g_networking": [
        "5g", "oran", "o-ran", "lte", "network function",
        "dpdk", "sdn", "ran engineer",
    ],
    "systems": [
        "systems programming", "kernel", "compiler", "llvm",
        "firmware", "embedded", "fpga",
    ],
    "backend": [
        "backend engineer", "distributed systems",
        "microservices", "api engineer",
    ],
    "web": [
        "frontend", "react", "typescript", "next.js",
        "full stack", "full-stack",
    ],
    "mobile": [
        "ios engineer", "android engineer", "mobile developer",
        "react native", "swift", "kotlin",
    ],
    "security": [
        "security engineer", "appsec",
        "offensive security", "red team",
    ],
    "devops": [
        "devops", "sre", "site reliability",
        "platform engineer", "infrastructure engineer",
    ],
}
